name = "jot"
version = "1.0.2"
gleam = ">= 0.39.0"
description = "A parser for Djot, a markdown-like language"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "jot" }
links = [
  { title = "Djot Syntax", href = "https://djot.net/syntax" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = "~> 0.39"

[dev-dependencies]
gleeunit = "~> 1.0"
simplifile = "~> 0.3"
filepath = "~> 0.1"
