name = "jot"
version = "5.0.0"
gleam = ">= 1.5.0"
description = "A parser for Djot, a markdown-like language"
licences = ["Apache-2.0"]
repository = { type = "github", user = "lpil", repo = "jot" }
links = [
  { title = "Djot Syntax", href = "https://djot.net/syntax" },
  { title = "Sponsor", href = "https://github.com/sponsors/lpil" },
]

[dependencies]
gleam_stdlib = ">= 0.54.0 and < 2.0.0"
splitter = ">= 1.0.0 and < 2.0.0"
houdini = ">= 1.1.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
simplifile = ">= 2.0.0 and < 3.0.0"
filepath = ">= 1.0.0 and < 2.0.0"
gleave = ">= 1.0.0 and < 2.0.0"
gleam_community_ansi = ">= 1.4.3 and < 2.0.0"
